# Generated by Django 4.0.4 on 2022-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_custom_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='custom_link',
            new_name='slug',
        ),
    ]
