# Generated by Django 4.0.4 on 2022-04-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_auth_users_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth_User',
            new_name='User',
        ),
    ]
