# Generated by Django 4.0.4 on 2022-05-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_auth_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
